"""empty message

Revision ID: 082d94629c7a
Revises: 504eb5e5da13
Create Date: 2025-08-07 11:04:10.110682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082d94629c7a'
down_revision: Union[str, Sequence[str], None] = '504eb5e5da13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'closemember', ['discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'closemember', type_='unique')
    # ### end Alembic commands ###
