"""empty message

Revision ID: 357599b767b0
Revises: 3cdf41d4704a
Create Date: 2025-08-01 13:24:48.329457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357599b767b0'
down_revision: Union[str, Sequence[str], None] = '3cdf41d4704a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    teamtype_enum = sa.Enum('DARK', 'LIGHT', name='teamtype')
    teamtype_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('userid', sa.BigInteger(), nullable=False),
    sa.Column('pos1games', sa.Integer(), nullable=False),
    sa.Column('pos1wins', sa.Integer(), nullable=False),
    sa.Column('pos2games', sa.Integer(), nullable=False),
    sa.Column('pos2wins', sa.Integer(), nullable=False),
    sa.Column('pos3games', sa.Integer(), nullable=False),
    sa.Column('pos3wins', sa.Integer(), nullable=False),
    sa.Column('pos4games', sa.Integer(), nullable=False),
    sa.Column('pos4wins', sa.Integer(), nullable=False),
    sa.Column('pos5games', sa.Integer(), nullable=False),
    sa.Column('pos5wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.add_column('closemember', sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.add_column('closemember', sa.Column('discord_id', sa.Integer(), nullable=False))
    op.add_column('closemember', sa.Column('pos', sa.Integer(), nullable=False))
    op.add_column('closemember', sa.Column('team', sa.Enum('DARK', 'LIGHT', name='teamtype'), nullable=False))
    op.drop_column('closemember', 'pos1games')
    op.drop_column('closemember', 'pos4games')
    op.drop_column('closemember', 'pos2games')
    op.drop_column('closemember', 'pos4wins')
    op.drop_column('closemember', 'userid')
    op.drop_column('closemember', 'pos5games')
    op.drop_column('closemember', 'pos1wins')
    op.drop_column('closemember', 'pos2wins')
    op.drop_column('closemember', 'pos3games')
    op.drop_column('closemember', 'pos3wins')
    op.drop_column('closemember', 'pos5wins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closemember', sa.Column('pos5wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos3wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos3games', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos2wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos1wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos5games', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('userid', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos4wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos2games', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos4games', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('closemember', sa.Column('pos1games', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('closemember', 'team')
    op.drop_column('closemember', 'pos')
    op.drop_column('closemember', 'discord_id')
    op.drop_column('closemember', 'id')
    op.drop_table('member')
    teamtype_enum = sa.Enum(name='teamtype')
    teamtype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
