"""empty message

Revision ID: 3cdf41d4704a
Revises: 9500b1d5fc0d
Create Date: 2025-07-31 17:20:49.567870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdf41d4704a'
down_revision: Union[str, Sequence[str], None] = '9500b1d5fc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('close', 'message',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('close', 'message',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
