"""empty message

Revision ID: 504eb5e5da13
Revises: 8029a31a8d48
Create Date: 2025-08-06 10:29:52.509774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504eb5e5da13'
down_revision: Union[str, Sequence[str], None] = '8029a31a8d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('closemember_close_id_fkey'), 'closemember', type_='foreignkey')
    op.create_foreign_key(None, 'closemember', 'close', ['close_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'closemember', type_='foreignkey')
    op.create_foreign_key(op.f('closemember_close_id_fkey'), 'closemember', 'close', ['close_id'], ['id'])
    # ### end Alembic commands ###
