"""empty message

Revision ID: 7caa2d62b533
Revises: 8ae92e40f699
Create Date: 2025-07-31 17:11:25.700378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7caa2d62b533'
down_revision: Union[str, Sequence[str], None] = '8ae92e40f699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('closemember_closeid_fkey'), 'closemember', type_='foreignkey')
    op.drop_column('closemember', 'closeid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closemember', sa.Column('closeid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('closemember_closeid_fkey'), 'closemember', 'close', ['closeid'], ['id'])
    # ### end Alembic commands ###
