"""empty message

Revision ID: 7ead7ed4b1f2
Revises: 
Create Date: 2025-07-26 18:52:02.631029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ead7ed4b1f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('close',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.Enum('COMMAND', 'RANDOM', name='closetype'), nullable=False),
    sa.Column('managechannel', sa.BigInteger(), nullable=False),
    sa.Column('waitingchannel', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('lastcall', sa.Integer(), nullable=False),
    sa.Column('message', sa.BigInteger(), nullable=False),
    sa.Column('messagechannel', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closemember',
    sa.Column('userid', sa.BigInteger(), nullable=False),
    sa.Column('closeid', sa.Integer(), nullable=False),
    sa.Column('pos1games', sa.Integer(), nullable=False),
    sa.Column('pos1wins', sa.Integer(), nullable=False),
    sa.Column('pos2games', sa.Integer(), nullable=False),
    sa.Column('pos2wins', sa.Integer(), nullable=False),
    sa.Column('pos3games', sa.Integer(), nullable=False),
    sa.Column('pos3wins', sa.Integer(), nullable=False),
    sa.Column('pos4games', sa.Integer(), nullable=False),
    sa.Column('pos4wins', sa.Integer(), nullable=False),
    sa.Column('pos5games', sa.Integer(), nullable=False),
    sa.Column('pos5wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['closeid'], ['close.id'], ),
    sa.PrimaryKeyConstraint('closeid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('closemember')
    op.drop_table('close')
    # ### end Alembic commands ###
