"""empty message

Revision ID: 8029a31a8d48
Revises: f4264de261ed
Create Date: 2025-08-06 10:06:25.893226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8029a31a8d48'
down_revision: Union[str, Sequence[str], None] = 'f4264de261ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userid', sa.BigInteger(), nullable=False),
    sa.Column('pos1games', sa.Integer(), nullable=False),
    sa.Column('pos1wins', sa.Integer(), nullable=False),
    sa.Column('pos2games', sa.Integer(), nullable=False),
    sa.Column('pos2wins', sa.Integer(), nullable=False),
    sa.Column('pos3games', sa.Integer(), nullable=False),
    sa.Column('pos3wins', sa.Integer(), nullable=False),
    sa.Column('pos4games', sa.Integer(), nullable=False),
    sa.Column('pos4wins', sa.Integer(), nullable=False),
    sa.Column('pos5games', sa.Integer(), nullable=False),
    sa.Column('pos5wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('userid', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('pos1games', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos1wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos2games', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos2wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos3games', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos3wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos4games', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos4wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos5games', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos5wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userid', name=op.f('member_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
