"""empty message

Revision ID: 84935abd1a20
Revises: cea1ff83e1e5
Create Date: 2025-08-01 13:57:01.403468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84935abd1a20'
down_revision: Union[str, Sequence[str], None] = 'cea1ff83e1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closemember', sa.Column('close_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'closemember', 'close', ['close_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'closemember', type_='foreignkey')
    op.drop_column('closemember', 'close_id')
    # ### end Alembic commands ###
