"""empty message

Revision ID: e43eefdb246b
Revises: df0f7c05f747
Create Date: 2025-07-29 20:48:02.791714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43eefdb246b'
down_revision: Union[str, Sequence[str], None] = 'df0f7c05f747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('close', 'lastcall',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('close', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('close', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('close', 'lastcall',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
